### ISSUE TITLE
'write_key' does not take blank value.

### ISSUE THREAD

**Issue by avinashtatras** [AltThree/Segment#14]
I configured the package with my project and configured the "write_key" in "segment.php" with an environment variable like this: 'write_key' => env('SEGMENT_WRITE_KEY_BACKEND', '').
Now segment throws the following error whenever the key is not present
"In Segment.php line 131:
                                                                    
  Segment::init() must be called before any other tracking method."

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch. Under what circumstances would the key be empty please?

**Comment by avinashtatras** [comment]
If an application is running in more than 1 environments and if I wanted the segment API to run in only one of them.

**Comment by GrahamCampbell** [comment]
That won't be easily possible, because of the poor design of the underlying segment package. You will have to avoid calling segment entirely yourself, by guarding every call I'm afraid.
