### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by MatanYadaev** [AltThree/Segment#22]

**Comment by GrahamCampbell** [comment]
Please raise an issue upstream with `segmentio/analytics-php`. They don't have a PHP 8.0 compatible release, yet.

**Comment by GrahamCampbell** [comment]
(That is, their package literally can be installed, but is untested, and doesn't actually work.)

**Comment by MatanYadaev** [comment]
@GrahamCampbell Can you please review my PR? https://github.com/AltThree/Segment/pull/25
