### ISSUE TITLE
Track events don't fire when called from a queued job

### ISSUE THREAD

**Issue by jbardnz** [AltThree/Segment#6]
Hey,

I am firing my Segment tracking events from a queued laravel event. The event fires correctly if I use the **sync** queue driver. But if I use **database** or **beanstalkd** then the segment code seems to silently fail. 

The job doesn't fail and nothing is logged but the data never shows up in Segment. Also note the rest of the code in the event handler function is being called.

Any ideas?

**Comment by jbrooksuk** [comment]
Assigned to @GrahamCampbell.

**Comment by jbardnz** [comment]
Hey guys,

Is their anything I can provide to help you out with this issue?

Thanks

**Comment by GrahamCampbell** [comment]
Is this still an issue?

**Comment by jbardnz** [comment]
Yes I believe this is still an issue.

**Comment by broadstreetboy** [comment]
@jbardnz I was helping a friend troubleshoot this for a few minutes today.   I think there is a 100 event batch setting configured by default.  If you are expecting a real time result you might not be seeing what you expect.  I saw bursts hit his log console in large batches.

**Comment by GrahamCampbell** [comment]
Ah, that would be it. We could do the same fix I implemented for Bugsnag, and send any ready events over:

https://github.com/bugsnag/bugsnag-laravel/blob/master/src/BugsnagServiceProvider.php#L132-L136. NB: this calls https://github.com/bugsnag/bugsnag-php/blob/master/src/Client.php#L313-L321 which calls https://github.com/bugsnag/bugsnag-php/blob/master/src/HttpClient.php#L87-L101.

**Comment by broadstreetboy** [comment]
@GrahamCampbell Awesome! I would appreciate a release for sending any ready events as otherwise I was going to spend next weekend looking into that.

**Comment by GrahamCampbell** [comment]
We're open to PRs to add this.

**Comment by GrahamCampbell** [comment]
Oops, shame I didn't pin those links to versions. All of them point to different bits of the code now! I think I know what I meant at the time though!

**Comment by GrahamCampbell** [comment]
Hopefully https://github.com/AltThree/Segment/pull/11 should fix this.
